name: Check Markdown Links

on:
  push:
    paths:
      - '**/*.md'
      - '.github/workflows/markdown-link-check.yml'

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Markdown Link Check
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'
          use-verbose-mode: 'yes'
          folder-path: '.'
          file-extension: '.md'